import type { LSystemPreset } from './types'

const STUDIO_PRESETS: LSystemPreset[] = [
  {
    id: 'verdant-bloom',
    name: 'Verdant Bloom',
    category: 'Botanical',
    description: 'A classic branching plant with delicate nested growth.',
    axiom: 'X',
    rules: {
      X: 'F+[[X]-X]-F[-FX]+X',
      F: 'FF',
    },
    drawSymbols: ['F'],
    defaultGenerations: 5,
    maxGenerations: 7,
    angle: 25,
    turnJitter: 2.4,
    step: 8,
    startAngle: -90,
    seed: 'first-light',
    appearance: {
      palette: { root: '#73523a', crown: '#75efae', accent: '#f6cf78' },
      trunkWidth: 6.5,
      taper: 0.73,
      glow: 7,
      showTips: true,
    },
  },
  {
    id: 'wild-canopy',
    name: 'Wild Canopy',
    category: 'Organic',
    description: 'The original experiment, evolved into a seeded living canopy.',
    axiom: 'X',
    rules: {
      X: 'F[[-X]+X]',
    },
    drawSymbols: ['F', 'X'],
    defaultGenerations: 11,
    maxGenerations: 15,
    angle: 24,
    turnJitter: 13,
    step: 9,
    startAngle: -90,
    seed: 'forest-echo',
    appearance: {
      palette: { root: '#9b5f49', crown: '#b9f56e', accent: '#fff0a3' },
      trunkWidth: 8,
      taper: 0.78,
      glow: 9,
      showTips: true,
    },
  },
  {
    id: 'paper-dragon',
    name: 'Paper Dragon',
    category: 'Curve',
    description: 'A precise dragon curve folded from a two-rule grammar.',
    axiom: 'FX',
    rules: {
      X: 'X+YF+',
      Y: '-FX-Y',
    },
    drawSymbols: ['F'],
    defaultGenerations: 12,
    maxGenerations: 16,
    angle: 90,
    turnJitter: 0,
    step: 7,
    startAngle: 0,
    seed: 'paper-fold',
    appearance: {
      palette: { root: '#7868ff', crown: '#5ee7f2', accent: '#f6a6ff' },
      trunkWidth: 2.4,
      taper: 1,
      glow: 10,
      showTips: false,
    },
  },
  {
    id: 'sierpinski-lace',
    name: 'Sierpiński Lace',
    category: 'Geometry',
    description: 'A triangular field woven from two mutually evolving symbols.',
    axiom: 'F-G-G',
    rules: {
      F: 'F-G+F+G-F',
      G: 'GG',
    },
    drawSymbols: ['F', 'G'],
    defaultGenerations: 6,
    maxGenerations: 9,
    angle: 120,
    turnJitter: 0,
    step: 7,
    startAngle: 0,
    seed: 'woven-light',
    appearance: {
      palette: { root: '#ff7895', crown: '#ffc96e', accent: '#fff3c7' },
      trunkWidth: 2.1,
      taper: 1,
      glow: 8,
      showTips: false,
    },
  },
]

export const CANONICAL_SYSTEMS: LSystemPreset[] = [
  {
    id: 'binary-tree',
    name: 'Binary Tree',
    category: 'Canonical',
    description: 'A balanced branching tree built from explicit turtle stacks.',
    axiom: '0',
    rules: {
      '0': '1[+0][-0]',
      '1': '11',
    },
    drawSymbols: ['0', '1'],
    defaultGenerations: 10,
    maxGenerations: 15,
    angle: 45,
    turnJitter: 0,
    step: 7,
    startAngle: -90,
    seed: 'binary-roots',
    appearance: {
      palette: { root: '#80533d', crown: '#a8ef72', accent: '#ffe09a' },
      trunkWidth: 5.6,
      taper: 0.78,
      glow: 6,
      showTips: true,
    },
  },
  {
    id: 'koch-snowflake',
    name: 'Koch Snowflake',
    category: 'Canonical',
    description: 'A closed curve whose three edges recurse into crystalline detail.',
    axiom: 'F--F--F',
    rules: {
      F: 'F+F--F+F',
    },
    drawSymbols: ['F'],
    defaultGenerations: 5,
    maxGenerations: 8,
    angle: 60,
    turnJitter: 0,
    step: 6,
    startAngle: 0,
    seed: 'winter-proof',
    appearance: {
      palette: { root: '#5877d9', crown: '#8fe8ff', accent: '#f4fbff' },
      trunkWidth: 2.1,
      taper: 1,
      glow: 9,
      showTips: false,
    },
  },
  {
    id: 'hilbert-curve',
    name: 'Hilbert Curve',
    category: 'Canonical',
    description: 'Mutual recursion folds one continuous path through a square.',
    axiom: 'A',
    rules: {
      A: '+BF-AFA-FB+',
      B: '-AF+BFB+FA-',
    },
    drawSymbols: ['F'],
    defaultGenerations: 6,
    maxGenerations: 8,
    angle: 90,
    turnJitter: 0,
    step: 6,
    startAngle: 0,
    seed: 'square-memory',
    appearance: {
      palette: { root: '#8d6df2', crown: '#62e6da', accent: '#e7d9ff' },
      trunkWidth: 2.2,
      taper: 1,
      glow: 8,
      showTips: false,
    },
  },
  {
    id: 'cantor-set',
    name: 'Cantor Set',
    category: 'Canonical',
    description: 'Draw and move symbols preserve a line while opening recursive gaps.',
    axiom: 'A',
    rules: {
      A: 'ABA',
      B: 'BBB',
    },
    drawSymbols: ['A'],
    moveSymbols: ['B'],
    defaultGenerations: 7,
    maxGenerations: 11,
    angle: 0,
    turnJitter: 0,
    step: 5,
    startAngle: 0,
    seed: 'middle-thirds',
    appearance: {
      palette: { root: '#f07a7a', crown: '#ffd36d', accent: '#fff2bd' },
      trunkWidth: 4.2,
      taper: 1,
      glow: 7,
      showTips: false,
    },
  },
  {
    id: 'gosper-curve',
    name: 'Gosper Curve',
    category: 'Canonical',
    description: 'Two drawable symbols interlock into a flowing hexagonal field.',
    axiom: 'A',
    rules: {
      A: 'A-B--B+A++AA+B-',
      B: '+A-BB--B-A++A+B',
    },
    drawSymbols: ['A', 'B'],
    defaultGenerations: 4,
    maxGenerations: 6,
    angle: 60,
    turnJitter: 0,
    step: 6,
    startAngle: 0,
    seed: 'hexagonal-river',
    appearance: {
      palette: { root: '#ff7f8f', crown: '#65e3ce', accent: '#fff0c7' },
      trunkWidth: 2.3,
      taper: 1,
      glow: 8,
      showTips: false,
    },
  },
]

export const PRESETS: LSystemPreset[] = [
  ...STUDIO_PRESETS,
  ...CANONICAL_SYSTEMS,
]

export function getPreset(id: string): LSystemPreset {
  return PRESETS.find((preset) => preset.id === id) ?? PRESETS[0]
}
