import type { LSystemPreset } from './types'

export const PRESETS: LSystemPreset[] = [
  {
    id: 'verdant-bloom',
    name: 'Verdant Bloom',
    category: 'Botanical',
    description: 'A classic branching plant with delicate nested growth.',
    axiom: 'X',
    rules: {
      X: 'F+[[X]-X]-F[-FX]+X',
      F: 'FF',
    },
    drawSymbols: ['F'],
    defaultGenerations: 5,
    maxGenerations: 7,
    angle: 25,
    turnJitter: 2.4,
    step: 8,
    startAngle: -90,
    seed: 'first-light',
    appearance: {
      palette: { root: '#73523a', crown: '#75efae', accent: '#f6cf78' },
      trunkWidth: 6.5,
      taper: 0.73,
      glow: 7,
      showTips: true,
    },
  },
  {
    id: 'wild-canopy',
    name: 'Wild Canopy',
    category: 'Organic',
    description: 'The original experiment, evolved into a seeded living canopy.',
    axiom: 'X',
    rules: {
      X: 'F[[-X]+X]',
    },
    drawSymbols: ['F', 'X'],
    defaultGenerations: 11,
    maxGenerations: 15,
    angle: 24,
    turnJitter: 13,
    step: 9,
    startAngle: -90,
    seed: 'forest-echo',
    appearance: {
      palette: { root: '#9b5f49', crown: '#b9f56e', accent: '#fff0a3' },
      trunkWidth: 8,
      taper: 0.78,
      glow: 9,
      showTips: true,
    },
  },
  {
    id: 'paper-dragon',
    name: 'Paper Dragon',
    category: 'Curve',
    description: 'A precise dragon curve folded from a two-rule grammar.',
    axiom: 'FX',
    rules: {
      X: 'X+YF+',
      Y: '-FX-Y',
    },
    drawSymbols: ['F'],
    defaultGenerations: 12,
    maxGenerations: 16,
    angle: 90,
    turnJitter: 0,
    step: 7,
    startAngle: 0,
    seed: 'paper-fold',
    appearance: {
      palette: { root: '#7868ff', crown: '#5ee7f2', accent: '#f6a6ff' },
      trunkWidth: 2.4,
      taper: 1,
      glow: 10,
      showTips: false,
    },
  },
  {
    id: 'sierpinski-lace',
    name: 'Sierpiński Lace',
    category: 'Geometry',
    description: 'A triangular field woven from two mutually evolving symbols.',
    axiom: 'F-G-G',
    rules: {
      F: 'F-G+F+G-F',
      G: 'GG',
    },
    drawSymbols: ['F', 'G'],
    defaultGenerations: 6,
    maxGenerations: 9,
    angle: 120,
    turnJitter: 0,
    step: 7,
    startAngle: 0,
    seed: 'woven-light',
    appearance: {
      palette: { root: '#ff7895', crown: '#ffc96e', accent: '#fff3c7' },
      trunkWidth: 2.1,
      taper: 1,
      glow: 8,
      showTips: false,
    },
  },
]

export function getPreset(id: string): LSystemPreset {
  return PRESETS.find((preset) => preset.id === id) ?? PRESETS[0]
}
